pool:
 VmImage: 'Windows-Latest'
variables:
  buildConfiguration: 'Building the code'
  DotnetSdkVersion: '6.x'
 

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK $(DotnetSdkVersion)'
    inputs:
      packageType: 'sdk'
      version: '$(DotnetSdkVersion)'

  - script: dotnet restore
    displayName: 'Restore project dependencies using dotnet CLI'

  - task: DotNetCoreCLI@2
    displayName: 'Build the project - $(buildConfiguration)'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration $(buildConfiguration)'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Pack the project - $(buildConfiguration)'
    inputs:
      command: 'pack'
      projects: '**/*.csproj'
      arguments: '--no-build --configuration $(buildConfiguration)'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '0'

  - task: NuGetCommand@2
    displayName: 'Publish NuGet package'
    inputs:
      command: 'push'
      feedPublish: '$(System.TeamProject)/Tailspin.SpaceGame.Web.Models'
      allowPackageConflicts: true
    condition: succeeded()
